apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    name: nginx-app
spec:
  containers:
  - name: nginx-app
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort:  80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20



---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    name: nginx-app
spec:
  type: NodePort
  selector:
    name: nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  

